# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  hkunetwork:

services:

# Orderer
  orderer.hku.com:
    container_name: orderer.hku.com
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.hku.com
    networks:
      - hkunetwork

# HKU
  peer0.athclub.hku.com:
    container_name: peer0.athclub.hku.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.athclub.hku.com
    networks:
      - hkunetwork

  peer1.athclub.hku.com:
    container_name: peer1.athclub.hku.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.athclub.hku.com
    networks:
      - hkunetwork

  peer0.hallA.hku.com:
    container_name: peer0.hallA.hku.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.hallA.hku.com
    networks:
      - hkunetwork

  peer1.hallA.hku.com:
    container_name: peer1.hallA.hku.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.hallA.hku.com
    networks:
      - hkunetwork

  peer0.hallB.hku.com:
    container_name: peer0.hallB.hku.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.hallB.hku.com
    networks:
      - hkunetwork

  peer1.hallB.hku.com:
    container_name: peer1.hallB.hku.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.hallB.hku.com
    networks:
      - hkunetwork

  peer0.hallC.hku.com:
    container_name: peer0.hallC.hku.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.hallC.hku.com
    networks:
      - hkunetwork

  peer1.hallC.hku.com:
    container_name: peer1.hallC.hku.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.hallC.hku.com
    networks:
      - hkunetwork

# CUHK
  peer0.clubA.cuhk.com:
    container_name: peer0.clubA.cuhk.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.clubA.cuhk.com
    networks:
      - hkunetwork

  peer0.clubB.cuhk.com:
    container_name: peer0.clubB.cuhk.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.clubB.cuhk.com
    networks:
      - hkunetwork

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.athclub.hku.com:7051
      - CORE_PEER_LOCALMSPID=AthClubMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/athclub.hku.com/peers/peer0.athclub.hku.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/athclub.hku.com/peers/peer0.athclub.hku.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/athclub.hku.com/peers/peer0.athclub.hku.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/athclub.hku.com/users/Admin@athclub.hku.com/msp
      - COMPOSE_PROJECT_NAME=hkunetwork
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    #command: /bin/bash -c './scripts/script.sh ${CHANNEL_NAME} ${DELAY} ${LANG}; sleep $TIMEOUT'
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.hku.com
      - peer0.athclub.hku.com
      - peer1.athclub.hku.com
      - peer0.hallA.hku.com
      - peer1.hallA.hku.com
      - peer0.hallB.hku.com
      - peer1.hallB.hku.com
      - peer0.hallC.hku.com
      - peer1.hallC.hku.com
      - peer0.clubA.cuhk.com
      - peer0.clubB.cuhk.com
    networks:
      - hkunetwork
